version: '3.3'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - ./data/db:/data/db
        networks:
            - mongodbnet
        ports:
            - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
        restart: unless-stopped

networks:
  mongodbnet:
  